#!/usr/bin/env python3
"""Apply a chunk plan to a .docx by inserting markers and flattening
selected tables in place, leaving everything else byte-for-byte untouched.

Usage:
    python3 apply_plan_docx.py <input.docx> <output.docx> <plan.json>

plan.json:
    {
      "insert_marker_after": [3, 7, 12],
      "flatten_tables": {"9": ["paragraph 1 text", "paragraph 2 text"], ...},
      "label_prefix": {"8": "开业前两天·"}
    }

- insert_marker_after: element indices (from inspect_docx.py's numbering);
  a standalone "<<<CHUNK>>>" paragraph is inserted right after each one.
- flatten_tables: table element indices to replace in place with the given
  paragraph texts (in order). If an index appears in both fields, the
  marker is anchored after the LAST replacement paragraph, not the
  (now-deleted) original table.
- label_prefix: paragraph element indices to prepend a short context prefix
  to (in place, first run only). The index must be the first element of a
  chunk (index 0, or immediately follows an insert_marker_after index) and
  must refer to a paragraph that already exists in the source document —
  it cannot point at a paragraph generated by flatten_tables. Use this to
  restate a distant heading on a chunk that would otherwise start mid-topic
  with no context of its own.

All indices are validated up front; nothing is written if any index is
invalid. Ends with a structural self-check of the output file.
"""

import json
import sys


def load_plan(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"error: could not read plan '{path}': {e}", file=sys.stderr)
        sys.exit(1)


def main():
    if len(sys.argv) != 4:
        print("usage: apply_plan_docx.py <input.docx> <output.docx> <plan.json>", file=sys.stderr)
        sys.exit(1)

    input_path, output_path, plan_path = sys.argv[1], sys.argv[2], sys.argv[3]

    if input_path == output_path:
        print("error: input and output paths must differ", file=sys.stderr)
        sys.exit(1)

    try:
        from docx import Document
        from docx.table import Table
        from docx.text.paragraph import Paragraph
        from docx.oxml import OxmlElement
    except ImportError:
        print("error: python-docx is not installed (pip install python-docx)", file=sys.stderr)
        sys.exit(1)

    plan = load_plan(plan_path)
    insert_marker_after = plan.get("insert_marker_after", [])
    flatten_tables_raw = plan.get("flatten_tables", {})
    label_prefix_raw = plan.get("label_prefix", {})

    try:
        doc = Document(input_path)
    except Exception as e:
        print(f"error: could not open '{input_path}': {e}", file=sys.stderr)
        sys.exit(1)

    items = list(doc.iter_inner_content())
    total = len(items)
    input_table_count = sum(1 for it in items if isinstance(it, Table))

    # --- validate everything before mutating anything ---
    errors = []

    def check_index(idx, label):
        if not isinstance(idx, int) or idx < 0 or idx >= total:
            errors.append(f"{label} index {idx!r} out of range [0, {total - 1}]")
            return False
        return True

    dedup_marker_indices = []
    seen = set()
    for idx in insert_marker_after:
        if idx in seen:
            print(f"warning: duplicate insert_marker_after index {idx}, ignoring repeat", file=sys.stderr)
            continue
        seen.add(idx)
        dedup_marker_indices.append(idx)

    for idx in dedup_marker_indices:
        check_index(idx, "insert_marker_after")
    dedup_marker_index_set = set(dedup_marker_indices)

    flatten_tables = {}
    for idx_str, paragraphs in flatten_tables_raw.items():
        try:
            idx = int(idx_str)
        except ValueError:
            errors.append(f"flatten_tables key {idx_str!r} is not an integer")
            continue
        if not check_index(idx, "flatten_tables"):
            continue
        if not isinstance(items[idx], Table):
            errors.append(f"flatten_tables index {idx} does not refer to a table element")
            continue
        if not paragraphs or not all(isinstance(p, str) and p.strip() for p in paragraphs):
            errors.append(f"flatten_tables[{idx}] must be a non-empty list of non-empty strings")
            continue
        flatten_tables[idx] = paragraphs

    label_prefix = {}
    for idx_str, prefix in label_prefix_raw.items():
        try:
            idx = int(idx_str)
        except ValueError:
            errors.append(f"label_prefix key {idx_str!r} is not an integer")
            continue
        if not check_index(idx, "label_prefix"):
            continue
        if not isinstance(items[idx], Paragraph):
            errors.append(f"label_prefix index {idx} does not refer to a paragraph element")
            continue
        if not isinstance(prefix, str) or not prefix.strip():
            errors.append(f"label_prefix[{idx}] must be a non-empty (trimmed) string")
            continue
        is_chunk_start = idx == 0 or (idx - 1) in dedup_marker_index_set
        if not is_chunk_start:
            errors.append(
                f"label_prefix index {idx} is not the first element of a chunk "
                "(must be index 0 or immediately follow an insert_marker_after index); "
                "label_prefix may only tag chunk-opening paragraphs, not mid-chunk text"
            )
            continue
        if not items[idx].runs:
            errors.append(f"label_prefix index {idx} paragraph has no runs to prefix")
            continue
        label_prefix[idx] = prefix

    if errors:
        for e in errors:
            print(f"error: {e}", file=sys.stderr)
        sys.exit(1)

    # --- resolve marker anchors before mutating (object refs stay valid) ---
    # default anchor for each index is the original element itself
    marker_anchor_object = {idx: items[idx] for idx in dedup_marker_indices}

    # --- apply table flattening: insert replacement paragraphs before the
    # table, then remove the table. Track the last inserted paragraph so a
    # marker requested at that same index anchors after the replacement.
    for idx, paragraphs in flatten_tables.items():
        table = items[idx]
        table_element = table._element
        parent_element = table_element.getparent()
        last_new_p = None
        for text in paragraphs:
            new_p = OxmlElement("w:p")
            table_element.addprevious(new_p)
            wrapped = Paragraph(new_p, table._parent)
            wrapped.add_run(text)
            last_new_p = new_p
        parent_element.remove(table_element)
        if idx in marker_anchor_object:
            marker_anchor_object[idx] = Paragraph(last_new_p, table._parent)

    # --- apply label prefixes: prepend text to the first run, in place ---
    expected_prefixed_text = {}
    for idx, prefix in label_prefix.items():
        target_paragraph = items[idx]
        # use the paragraph's full .text (not just runs[0]) so this stays
        # correct even if the paragraph has more than one run
        expected_prefixed_text[idx] = prefix + target_paragraph.text
        target_paragraph.runs[0].text = prefix + target_paragraph.runs[0].text

    # --- apply marker insertion ---
    for idx in dedup_marker_indices:
        anchor = marker_anchor_object[idx]
        new_p = OxmlElement("w:p")
        anchor._element.addnext(new_p)
        marker_paragraph = Paragraph(new_p, anchor._parent)
        marker_paragraph.add_run("<<<CHUNK>>>")

    doc.save(output_path)

    # --- structural self-check on the saved output ---
    self_check_failures = []
    try:
        out_doc = Document(output_path)
    except Exception as e:
        print(f"SELF-CHECK: FAIL - could not reopen output file: {e}", file=sys.stderr)
        sys.exit(1)

    out_items = list(out_doc.iter_inner_content())
    out_table_count = sum(1 for it in out_items if isinstance(it, Table))
    expected_table_count = input_table_count - len(flatten_tables)
    if out_table_count != expected_table_count:
        self_check_failures.append(
            f"expected {expected_table_count} tables in output, found {out_table_count}"
        )

    marker_positions = [
        i for i, it in enumerate(out_items)
        if isinstance(it, Paragraph) and it.text.strip() == "<<<CHUNK>>>"
    ]
    if len(marker_positions) != len(dedup_marker_indices):
        self_check_failures.append(
            f"expected {len(dedup_marker_indices)} marker paragraphs, found {len(marker_positions)}"
        )
    if marker_positions and marker_positions[0] == 0:
        self_check_failures.append("a marker paragraph is the first element in the document body")
    if marker_positions and marker_positions[-1] == len(out_items) - 1:
        self_check_failures.append("a marker paragraph is the last element in the document body")

    if label_prefix:
        out_texts = [it.text for it in out_items if isinstance(it, Paragraph)]
        for idx, expected_full in expected_prefixed_text.items():
            if expected_full not in out_texts:
                self_check_failures.append(
                    f"label_prefix[{idx}]: expected paragraph text not found in saved output "
                    f"(expected exact text {expected_full!r})"
                )

    if self_check_failures:
        print("SELF-CHECK: FAIL")
        for f in self_check_failures:
            print(f"  - {f}", file=sys.stderr)
        sys.exit(1)

    print("SELF-CHECK: PASS")


if __name__ == "__main__":
    main()
